### ISSUE TITLE
Semantic versioning for mods

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#12]
In BCML, the version for a mod was a string. This allowed semantic versioning, like 3.0.1, 1.9.13, etc (though I'm unsure whether that was actually used anywhere).

It seems in UKMM the corresponding field uses a float value instead, leaving the best one can do at something like 3.01, or 1.0913, or maybe 19.13... Any way you do it, it's unclear what version the mod actually is. And, unlike BCML, the version is visible.

Allowing semantic versioning would be much appreciated.

**Comment by NiceneNerd** [comment]
I seriously considered semantic versioning in the early design phase, but two considerations led me to the simpler format:
- It's not entirely intuitive what changes or lack thereof the major/minor/patch versions would necessarily refer to for mods. A definition could be provided, but adoption may very well not follow.
- Related to the last clause, based on my experience with mod authors in the past they tend to be very ad hoc in their versioning and don't often have a mind for anything consistent, limiting its usefulness if adoption and implementation is haphazard.

I am open to reconsidering this, though, given a good account of, well, what the actual semantics should be.

**Comment by Benna96** [comment]
I can only speak for myself, and my experience with modding is pretty limited.

Firstly, the main thing that bothers me about it is the discrepancy, since you can semantically version mods on GameBanana and mods are known by that semantically versioned version, for those who look at the version anyway. Having the version be different in UKMM is... odd.

Now, as for my personal definition for major/minor/patch:  

Major is a remake of almost the entire mod. See Linkle 2 vs Linkle 3.  
Minor is additions.  
Patch is bugfixes and tweaks to existing features.  

Compatibility patches for other mods I'd put in either patch or minor, depending on how complex they are... But perhaps they should just be patch for simplicity, seeing as how it's literally called patch.

That's just me and my small mods... I don't know if that definition would work for, say, Second Wind.

I'd like to get lots of other people's opinions, reach some kind of consensus. Posted the issue on the modding hub, inviting people to discuss.

**Comment by ArchLeaders** [comment]
I'm used to using semantic versioning, although only 2 numbers (minor/patch) would work fine for my uses. In most cases, a complete rewrite is also a new mod (e.g. Linkle 2, Linke 3)

However, I don't necessarily see the point in disallowing semantic versioning. It seems like a pointless restriction that might just be an annoyance for those people used to semantic versioning (if *those people* exist at all).

**Comment by Torphedo** [comment]
I do use semantic versioning on my mods, though I admit it's not particularly consistent. I completely agree that most mod authors are also very inconsistent with versioning, but regardless of that, it would make it easier for users to distinguish between 2 builds. And as Arch said, the lack of semantic versioning may be a hindrance for some people

**Comment by GingerAvalanche** [comment]
Semantic versioning, as a term, includes the purpose of the numbers in the definition: https://semver.org/ Major is breaking changes, minor is backwards-compatible additions, patch is backwards-compatible bugfixing. So, by calling it semantic versioning, we already define what the numbers mean.

We would need some level of multi-number versioning, even if it wasn't semantic. If we just leave versions as floats, then, for example, 3.9 will be a "higher" patch than 3.10, and 3.1 and 3.10 would be seen as the same.

My vote is for semantic versioning, even though I don't really think we need more than minor/patch, as I have yet to see evidence that any mods are capable of making breaking changes. (Since there's no API, "breaking changes" are defined here as changes that make a save file from a previous version of the mod incompatible with a save file of the new version.) That would require us to be able to edit save serde, which won't be possible until if/when the decomp project allows us to rebuild the executable. So, barring someone misusing it, every mod would either be 0.something or 1.something

**Comment by NiceneNerd** [comment]
Yea, it's precisely the fact that there's no "API" per se to make breaking changes an especially clear concept which left me with questions about the semantics. However, I do think we're capable of certain kinds of "breaking changes" already. For example, an item could be renamed or removed, leaving it to disappear from the inventory, or changes to game data flags themselves could cause very funky behavior after upgrading (e.g. changes to inventory slots and such). Changes in the structure of a quest could break progression, or other similar things.

I think, though, I'll go ahead and proceed with proper semver. For most mods it may be pretty irrelevant, and some people will continue to drive me nuts by insisting to put version numbers into the titles, but for projects where it would make sense and the authors would prefer it, it might as well be supported.
