### ISSUE TITLE
Deleting a mod makes UKMM stop working entirely (dosen't even open) (UPDATE)

### ISSUE THREAD

**Issue by neocpu** [NiceneNerd/ukmm#147]
so, I might have the blessing of breaking software in ways no dev expects, but somehow I did, I have no idea what, I was just trying to delete some mod, then it appeared a error, something like "no key" or "invalid key", and them BOOM, when I closed it, gone, now couldn't open, re-installing (more to re-download) didn't fix anything, besides giving me a ""new"" exe, I had to start my load order and merges again.

I would consider this something that severely hinders the reliability of the software, although this dosent inpact much (if you do not clear your download folder that is)

if this happens again I will try to get the exact error message

**Comment by neocpu** [comment]
so, as an update, this appears to be related with the fact that, the apply changes UI nevers get deactivated (or un-interactible) during uninstalls, installs and etc, i havent got to it happen again (cuz now i avoid uninstalling as much as possible) but this appears to be something you wont see much

**Comment by neocpu** [comment]
i  got the error again...
no entry found for key
![error cause](https://github.com/NiceneNerd/ukmm/assets/138073080/f1729de6-20f5-4fa3-b29c-304d89e8052d)
![itself](https://github.com/NiceneNerd/ukmm/assets/138073080/da527156-2769-44a6-9a88-8cc212dfd570)

**Comment by DimitriPilot3** [comment]
I got the error a few times (on 0.10.1 release) and eventually couldn't start UKMM anymore. Running `ukmm.exe` from the command line gave me the following output:

````
thread 'main' panicked at 'no entry found for key', crates\uk-manager\src\mods.rs:208:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
An unrecoverable error occured. Error details: no entry found for key
````

The panic occurs at [crates\uk-manager\src\mods.rs:208:18](https://github.com/NiceneNerd/ukmm/blob/93ce68debd163570e79be7bf14dd5085a5f072ea/crates/uk-manager/src/mods.rs#L208C6-L208C38). I do have a full stack backtrace with `set RUST_BACKTRACE=full` but do not have any program symbols on it. (I'd need to build UKMM from source.)

More importantly, I found that this particular panic was caused, in `profile.yml`, by one item in the `load_order` array referring to a deleted mod (whose key doesn't exist in the `mods` dictionary). For instance, this [profile.yml](https://github.com/NiceneNerd/ukmm/files/14324771/profile.yml.txt) reproduces the UKMM panic on startup; the culprit is the last line that reads `- 4042239387264041816`. Deleting this line makes UKMM able to start normally.
