### ISSUE TITLE
doesn't work no matter what i do 

### ISSUE THREAD

**Issue by goons2goblins** [NiceneNerd/UKMM#173]
Can't install SW, can't install any other shit, there's no freaking how-to, this is not plug n play SMFH

"Failed to apply pending mod changes

Caused by:
    No copy of Actor/Pack/Enemy_Golem_Little_Fire.sbactorpack found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates\uk-mod\src\unpack.rs@720:14`"

My game dump and dlc and update haven't been a problem for the past 3-4 years of using BCML on my older computer.  I actually started a fresh cemu folder with everything, and I am completely unable to get mods to 1) install and then 2) display in game. 

The deployment file isn't necessarily explained, neither is the one next to it, please help.

**Comment by NiceneNerd** [comment]
Why do you claim there is no how-to when there is in fact a guide? It explains in detail the things you said weren't explained.

Anyway, this error could have a few causes, but if you get it with Second Wind it could be because SW has some compatibility issues with UKMM they are actively working on fixing.
