### ISSUE TITLE
Getting [ERROR]: Mod is for Specific(Big), current mode is Switch

### ISSUE THREAD

**Issue by Ivydevdre** [NiceneNerd/UKMM#182]
When I try to add certain mods I get the error: [ERROR]: Mod is for Specific(Big), current mode is Switch and it cannot be added.

I checked in the bnp files and in info.json it is defined as a switch mod

**Comment by Ivydevdre** [comment]
[better_armors - Copy.zip](https://github.com/user-attachments/files/16098931/better_armors.-.Copy.zip)
[craftingproject_c042f_switch.zip](https://github.com/user-attachments/files/16098932/craftingproject_c042f_switch.zip)
Here are two mods that do that. I've changed their extensions from bnp to zip so I can upload them.

**Comment by Ivydevdre** [comment]
Or gamebanana links https://gamebanana.com/mods/358261

**Comment by NiceneNerd** [comment]
Both mods have different problems.

The Crafting Project has both a `rules.txt` and an `info.json` file, which confuses the BNP converter into thinking it is a Wii U mod. For this I can provide a workaround in UKMM. In the meantime you can just delete the `rules.txt` from within the mod.

The Better Armors mod you uploaded *is* actually a Wii U mod, not a Switch mod, and on top of that it has the bonus error of using a `Content` folder instead of a `content` folder.
