### ISSUE TITLE
Symlink deploy mode: profile switching broken

### ISSUE THREAD

**Issue by ilonachan** [NiceneNerd/UKMM#199]
I'm on Linux, and so obviously I use the Symlink function to deploy mods into UKMM's output directory (of which I've then again symlinked the two title IDs to my emulator's mod directory). It worked perfectly, until I tried to work with different profiles: the symlink didn't get updated when I switched.

Looking at the code, I see exactly why this happens: the deployment only checks if there is ANY symlink, but doesn't correct that symlink to point to the correct profile. This logic error should be easy enough to fix though; even just blindly deleting the existing symlink and then immediately recreating the correct one shouldn't cause issues.

**Comment by GingerAvalanche** [comment]
This was originally not implemented because the Rust std lib enjoys debating about how to fix cross-filesystem access issues, instead of actually fixing them, so there's no *real* good way to ensure cross-platform link removal (and is why, if you switch from symlink to copy deployment methods, you get an error telling you to delete the previous link).

I think I've found a simple way to ensure it works cross-filesystem, though. I'll need to test to make sure it doesn't delete system32 randomly, but I think this should be part of 0.14.0
