### ISSUE TITLE
Zelda's Ballad Texture Issues

### ISSUE THREAD

**Issue by CoherentThought** [NiceneNerd/UKMM#205]
The textures of the player model when playing with the Zelda's Ballad mod has issues, as shown below: 
![zelda_texture_glitch](https://github.com/user-attachments/assets/e4b81274-1364-45f7-86f7-61a6aca64cc4)

UKMM version: 0.13.0

These errors pop up in the cemu logging window. Unsure if this is relevant.
![LogRatioMismatch](https://github.com/user-attachments/assets/4f41c0ae-a3a7-46d4-8fbc-0eef8994cb09)

**Edit:**

Mod has an extra file it shouldn't have. You can manually fix the mod by following these steps:
* Unpack the zip
* Go to content/Model/
* Remove Link.Tex2.sbfres
* Repackage as 7z

**Comment by GingerAvalanche** [comment]
I use Zelda's Ballad in all my testing (I don't even play the game without it. Curse Nintendo for taking it down) and don't see this issue.

![image](https://github.com/user-attachments/assets/6eb21ab3-ab03-4f82-bd67-e19c25d32bb2)

Are you sure your dumps are correct? She's using the regular Link skeleton in your screenshot, not the Zelda's Ballad skeleton, so it looks like UKMM wasn't able to merge TitleBG.pack

**Comment by CoherentThought** [comment]
Other mods seem to work fine and I'm not receiving errors when installing it. Others have also reported the same issue as me. You just installed it normally? Regarding the skeleton, I use the links animation version.

Also, it works if I import it as a graphics pack, but then I can't add other mods.
![working_zelda](https://github.com/user-attachments/assets/ccb5a5d3-bf16-46ba-9b3f-117f8e5565f8)

**Comment by GingerAvalanche** [comment]
There were some subtle bugs with Zelda's Ballad that I fixed a loooong time ago. Nothing that would cause this, just some orphaned references that UKMM would accept. But I probably ended up repackaging the mod in a different way than Amiibolad had it, originally, so it just installed for me because I know how to repackage mods.

What do you mean by "then I can't add other mods"? There's no reason you couldn't add mods if installing from a graphics pack. That's what UKMM is designed for.

**Comment by CoherentThought** [comment]
I mean installing it manually without UKMM. The mod works when installed as a graphics pack through cemu, but not when installed through UKMM.

**Comment by GingerAvalanche** [comment]
Well, the errors you're getting are related to textures. This means `.sbfres` files. UKMM doesn't have a library for opening or reading `.sbfres` files, so all it can do is move the ones from the mod into the proper places in the merge. It cannot touch their contents.

The only thing it could do is create RSTB entries that didn't work for the texture files. This is incredibly unlikely, though, as texture archives are one of the few easily-calculable types. BCML was able to calculate them accurately 4-5 years ago, and UKMM's RSTB calculation is better, in every way that it *can* be better, than BCML's was.

This is a long-winded way of saying that I have absolutely no clue how this could be happening, and without some more information, I won't be able to do anything about it. I encourage you to find `content/Model/Link.Tex1.sbfres`, and download [Wild Bits](https://gamebanana.com/tools/6660) and open `content/Pack/TitleBG.pack` and find `Model/Link.Tex2.sbfres`, and compare them to the ones you installed as a graphic pack, using [Switch Toolbox](https://github.com/KillzXGaming/Switch-Toolbox). I'd be interested to see if you find anything different between the two sets of files, though I'm fairly positive it's not even possible for them to be different.

**Comment by CoherentThought** [comment]
Unfortunately I don't have windows. Is there a linux alternative of some kind for switch toolbox?
Wild bits seems to open in a debugging session :S
I'm not very comfortable with python.

I extracted titleBG.pack from the game files using sarc And got Link.Tex2.sbfres from there.

Anyways, since I can't open the files here they are in audacity:
![forgive_me](https://github.com/user-attachments/assets/84698d0e-d99d-478f-973d-c43a34c4a0e4)

**Comment by GingerAvalanche** [comment]
Oh, you're on Linux? Use the appimage from [here](https://github.com/NiceneNerd/Wild-Bits/releases/tag/v2.0.0-beta3).

Comparing the files from base game to mod doesn't really help, as we're comparing Link to Zelda. We should compare them from pre-install files to post-merge files. That's how we know the exact file from the archive is being moved to the merge without changes.

**Comment by CoherentThought** [comment]
I was afraid I was comparing the wrong files. Thank you for your patience. You are right, there is at least one duplicate file in the wrong location. Does this impact UKMM in any way to your knowledge? I will try removing it to see if it makes a difference. Any other repackaging tips?

![The files appear to be different.](https://github.com/user-attachments/assets/26614f01-3662-4bca-bafe-dc35c7743774)
The files appear to be different.

**Comment by CoherentThought** [comment]
Oh! Removing the extra file completely fixed the mod in UKMM.

So to summarize for others:
* Unpack the zip
* Go to content/Model/
* Remove Link.Tex2.sbfres
* Repackage as 7z

Thanks, Ginger <3

Is this something UKMM could possibly autodetect and deal with, or would that potentially break or disallow stuff?

**Comment by GingerAvalanche** [comment]
A file appearing at the same canonical path twice, once inside an archive and once outside, might be the culprit. I'm not sure this should be something UKMM handles, since, if they're different, UKMM doesn't know which file is the correct one to use. In this specific case, the one inside TitleBG is the one that the game will load, because GameROMPlayer is a resident actor. But is the mod Tex2 inside TitleBG the one that is made correctly?

In fact, I'm not confident of anything right now. The replacement animation and Link's animation *should* be the same for these files. Texture archives are completely separate from model/animation archives, despite being the same file type. I can't think of a good reason why they'd be different, much less why the bigger `Mod` full-sizes would have mipmaps a quarter of their size while the smaller `UKMM` full-sizes would have mipmaps almost equal to them in size (Tex1 is full-size, Tex2 is mipmaps).

**Comment by CoherentThought** [comment]
The Tex2 in the titlebg and the one outside are identical as far as I could see, it seems to be the output that breaks.

How about a warning in the log indicating that multiples have been detected and what they are called? Would that be doable? It would allow people to manually fix things, and would make it easier to know why something is breaking.

**Comment by GingerAvalanche** [comment]
The symptoms you had were just regular displaced mipmaps, which happens when mips for one texture are applied to a different texture. So what I think actually happened was the presence of the file both inside and outside an archive caused the file to be logged as belonging outside an archive, and then when merging, UKMM left the vanilla mipmaps inside the archive, so the game used Zelda's textures with Link's mipmaps.

I agree with the warning. Maybe it would also be a good idea to ensure duplicate canonical paths get their real paths that contain archives logged, instead of getting the real paths that don't. That would've solved your problem in the first place.

**Comment by CoherentThought** [comment]
Should I mark this issue as closed ?

More logging is always very handy !

**Comment by GingerAvalanche** [comment]
Nah, leave it open. It’s actionable. I’ll close it with a commit when I make the changes

**Comment by NiceneNerd** [comment]
So after discussing this with Ginger further, the expected solution wouldn't actually apply to Zelda's Ballad, since it has different versions of the mips inside and outside TitleBG.pack, and UKMM can't actually know which version of the file is the right one. It just uses whichever it finds first, which due purely to accidents of sorting and speed will probably always be the one outside of the pack. And neither UKMM nor BOTW's engine supports having two incompatible versions of a file with the same canonical path. 

While there might be a clever hack we could use to catch problems like this, that would probably carry an undesirable performance penalty for something that affects a small number of very old mods and one mod Nintendo recently DCMA'd.

**Comment by A-nonymous027** [comment]
I found another duplicate messing up the texture of Zelda's Sheikah Slate belt and her default pant.
It's Armor_Default.Tex2.sbfres. Deleting it from the mod fixes the issue.

**Comment by sv-memes1** [comment]
Hey, sorry to necro this issue, but I'm having the same one. Downloaded the mod from an archive I found in DuckDuckGo (tell me if it's safe to link), the last edited date is June 29, 2020, and I tried doing what CoherentThought did, to no avail. Deleted Link.Tex2.sbfres from UKMM's mod folder, from the downloaded .rar... From everywhere I could find, really.

Running Cemu-2.6-x86_64.AppImage in my Fedora Workstation 44 + GNOME 50. The Switch port works fine for Ryujinx, but @ 13 FPS... While CEMU has FPS++ that gets me stable 50.

What am I doing wrong?
