### ISSUE TITLE
Fails to convert BNP to UKMM mod on Nobara (Fedora based)

### ISSUE THREAD

**Issue by udese** [NiceneNerd/UKMM#218]
As always, sorry if that was already known but I couldn't find anything resembling my error.
Happens with both 0.15 & 0.11.1. So maybe caused by a system update? I haven't managed my mods in months.

With system 7z:
```
[ERROR]: Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack translucent_hearts.bnp at `crates/uk-manager/src/bnp.rs@522:42`
    1: Failed to extract BNP at `crates/uk-manager/src/bnp.rs@488:36`
    2: 
       ERROR: E_FAIL
```

Without sysstem 7z:
```
[ERROR]: Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack translucent_hearts.bnp at `crates/uk-manager/src/bnp.rs@522:42`
    1: Failed to extract BNP at `crates/uk-manager/src/bnp.rs@488:36`
    2: Io(Os { code: 28, kind: StorageFull, message: "No space left on device" }, "")
```

**Comment by GingerAvalanche** [comment]
UKMM doesn't use BNPs internally, this would have to be caused by something you're currently actively installing, so we know it's not to do with your previously-installed mods.

BCML uses its own, internally-supplied 7zip exe that is likely just an older version of the one that UKMM uses when you choose the option to use your system 7z. So there should be no functional difference between using the system 7z and using BCML, which makes me think BCML would also fail to install this mod.

Based on the error message when not using system 7z, you just don't have enough space on your drive to unpack the bnp into your temp files. Maybe check the drive your temp files are on to ensure you have available space.

**Comment by NiceneNerd** [comment]
That is what I was going to ask: what's your system temp folder look like?

**Comment by udese** [comment]
Sorry for forgetting some important information, I just didn't think of it since I knew that couldn't be the cause: 
my main partition (which is only 50gb since it's more than enough) has got 27gb left and my home partition, 314gb.

The mod I used for testing was [Translucent Hearts](https://gamebanana.com/mods/308928). I installed it before without problem. all mods I attempt to install fail.

**Comment by GingerAvalanche** [comment]
All mods? Or just bnp’s? 7zip is only used for bnp’s so if all mods fail then you would get a different error for other mods.

If you’ve only tried bnp’s, then Translucent Hearts has a regular graphic pack download you could try.

I’ve gotten out of memory errors when compressing with 7zip due to it trying to use more than 4 cores to compress, which requires more RAM than the program can use (I can give it more, but can’t figure out how to make it use more). That’s not decompression - your issue - but might be related.

**Comment by udese** [comment]
update: just restarting the computer makes the issue go away.
I unfortunately wouldn't be able to reproduce the issue since I don't think I did anything in particular other than updating at first.
