### ISSUE TITLE
Storage Folder directory not affected by the Portable Flag

### ISSUE THREAD

**Issue by LucavaL** [NiceneNerd/ukmm#40]
Running ukmm with the `--portable` flag won't prevent the creation of a _ukmm_ folder in _%localappdata%_ .

**OS:** Windows 10 Home 19045.2546
**UKMM Version:** Latest Pre-Release (0.3.0)

**Comment by RLGingerBiscuit** [comment]
Currently the portable flag only affects the settings, not where the mods are stored as described in the book:

> You can alternatively launch UKMM with the `--portable` flag, in which case it will use a config folder next to the UKMM executable.

You can change where the mods are stored via the Storage Folder option in the settings
![image](https://user-images.githubusercontent.com/29359076/220123078-0add69e5-ebbf-49c8-8def-a57e96c526f8.png)

I won't be the one to decide whether that changes or not, but that's why the folder is still created.
