### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by foresto** [NiceneNerd/ukmm#77]
The build fails with the current nightly rust toolchain: 

rustc 1.70.0-nightly (3a8a131e9 2023-04-02)

Regardless of whether I build from the release branch, master, or a recent git tag, it fails with lots of errors like these:

    error[E0658]: use of unstable library feature 'lazy_cell'
     --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rstb-0.6.0/src/botw.rs:1:33
      |
    1 | use std::{collections::HashMap, sync::LazyLock};
      |                                 ^^^^^^^^^^^^^^
      |
      = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
      = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

**Comment by NiceneNerd** [comment]
Yeah, they just stabilized *some* of the `once_cell` features, but not the lazy stuff. Now the lazy stuff is under a different feature flag. Unfortunately, I can't update it yet because the GitHub workflows require a pre-1.70 Rust nightly in order to avoid a new bug building one of the dependencies on macOS. In the meantime, I recommend using the `nightly-2023-02-28` toolchain.
