### ISSUE TITLE
Failed to apply pending mod changes (Hyrule Rebalance)

### ISSUE THREAD

**Issue by Audixas** [NiceneNerd/ukmm#96]
I get this error trying to refresh the merge:

Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_298_Upper.sbactorpack at `crates\uk-mod\src\unpack.rs@679:22`
    1: Failed to build file Actor/ActorLink/Armor_298_Upper.bxml for SARC at `crates\uk-mod\src\unpack.rs@701:18`
    2: No base version for file Actor/ActorLink/Armor_298_Upper.bxml at `crates\uk-mod\src\unpack.rs@632:14`

At first I had issues with other mods as well (Linkle 3.0 and Girly Animations), but now it merges fine as long as Hyrule Rebalance is not enabled.

**Comment by Benna96** [comment]
Not sure if this is related, but I had a similar thing with Linkle 3.0.1 BNP, until I wasn't...  
You may be on to something with restart.

Here's exactly what I did, in case that's helpful.

I had a custom conversion of Linkle 3.0.1 already installed.  
1. Tried installing the BNP. UKMM said no because my custom conversion of the same name was there.
2. Uninstalled custom conversion, installed the BNP with all options.
3. Deployed. Got an error message similar to Audixas'. In my case it was complaining about `Physics/Cloth/Armor_175/Armor_175_Upper.hkcl` inside `Actor/Pack/Armor_017_Upper.sbactorpack`.
4. Hit deploy again. No complaints.
5. Uninstalled the mod.
6. Restarted UKMM.
7. The error is no more, no matter what I do. Can't recreate it. I can install & uninstall the bnp & my own conversion in the same session without problems. Mod works fine.
